package com.runanywhere.sdk.features.tts

import android.media.AudioAttributes
import android.media.AudioFormat
import android.media.AudioTrack
import com.runanywhere.sdk.foundation.SDKLogger
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlinx.coroutines.withContext
import java.util.concurrent.atomic.AtomicBoolean
import java.util.concurrent.atomic.AtomicInteger
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

/**
 * Manages audio playback for TTS services on Android.
 * Plays WAV audio data (8-bit or 16-bit PCM format) generated by TTS synthesis.
 *
 * Matches iOS AudioPlaybackManager behavior.
 */
class AudioPlaybackManager {
    private val logger = SDKLogger.tts
    private val playbackIdGenerator = AtomicInteger(0)

    @Volatile
    private var audioTrack: AudioTrack? = null

    @Volatile
    private var interruptPlayback: (() -> Unit)? = null

    @Volatile
    var isPlaying: Boolean = false
        private set

    /**
     * Play WAV audio data asynchronously.
     *
     * @param audioData WAV audio data to play (including WAV header)
     * @throws AudioPlaybackException if playback fails
     */
    suspend fun play(audioData: ByteArray) {
        if (audioData.isEmpty()) {
            throw AudioPlaybackException.EmptyAudioData
        }

        val playbackId = playbackIdGenerator.incrementAndGet()
        logger.debug("[playbackId=$playbackId] play() start: totalBytes=${audioData.size}")

        withContext(Dispatchers.IO) {
            try {
                val wavInfo = parseWavHeader(audioData)
                logger.info("[playbackId=$playbackId] Playing audio: ${audioData.size} bytes, ${wavInfo.sampleRate}Hz, ${wavInfo.channels}ch, ${wavInfo.bitsPerSample}bit")

                val pcmData = audioData.copyOfRange(wavInfo.dataOffset, audioData.size)

                playPcmData(playbackId, pcmData, wavInfo.sampleRate, wavInfo.channels, wavInfo.bitsPerSample)

                logger.info("[playbackId=$playbackId] play() completed")
            } catch (e: Exception) {
                logger.error("[playbackId=$playbackId] play() failed: ${e.message}")
                throw if (e is AudioPlaybackException) e else AudioPlaybackException.PlaybackFailed(e.message)
            }
        }
    }

    /**
     * Stop current playback. If play() is suspended, it will resume with PlaybackInterrupted.
     */
    fun stop() {
        logger.debug("stop() called: isPlaying=$isPlaying, hasTrack=${audioTrack != null}")
        interruptPlayback?.invoke()
    }

    private suspend fun playPcmData(
        playbackId: Int,
        pcmData: ByteArray,
        sampleRate: Int,
        channels: Int,
        bitsPerSample: Int,
    ) = suspendCancellableCoroutine { continuation ->
        val resumed = AtomicBoolean(false)

        fun cleanup(track: AudioTrack?) {
            isPlaying = false
            try { track?.stop() } catch (_: Exception) {}
            try { track?.release() } catch (_: Exception) {}
            if (audioTrack === track) audioTrack = null
            interruptPlayback = null
        }

        fun succeed(track: AudioTrack?) {
            val casWon = resumed.compareAndSet(false, true)
            logger.debug("[playbackId=$playbackId] completion path=success casWon=$casWon")
            if (casWon) {
                cleanup(track)
                continuation.resume(Unit)
            }
        }

        fun fail(track: AudioTrack?, throwable: Throwable) {
            val casWon = resumed.compareAndSet(false, true)
            logger.debug("[playbackId=$playbackId] completion path=${throwable::class.simpleName} casWon=$casWon")
            if (casWon) {
                cleanup(track)
                continuation.resumeWithException(throwable)
            }
        }

        try {
            logger.debug("[playbackId=$playbackId] playPcmData() enter: pcmBytes=${pcmData.size}, sampleRate=$sampleRate, channels=$channels, bitsPerSample=$bitsPerSample")

            val channelConfig =
                if (channels == 1) AudioFormat.CHANNEL_OUT_MONO else AudioFormat.CHANNEL_OUT_STEREO

            val audioFormat =
                when (bitsPerSample) {
                    8 -> AudioFormat.ENCODING_PCM_8BIT
                    16 -> AudioFormat.ENCODING_PCM_16BIT
                    else -> {
                        logger.debug("[playbackId=$playbackId] completion path=unsupported_bit_depth bitsPerSample=$bitsPerSample")
                        continuation.resumeWithException(AudioPlaybackException.InvalidAudioFormat)
                        return@suspendCancellableCoroutine
                    }
                }

            val minBufferSize = AudioTrack.getMinBufferSize(sampleRate, channelConfig, audioFormat)

            if (minBufferSize == AudioTrack.ERROR || minBufferSize == AudioTrack.ERROR_BAD_VALUE) {
                logger.warn("[playbackId=$playbackId] Invalid minBufferSize=$minBufferSize")
                continuation.resumeWithException(AudioPlaybackException.InvalidAudioFormat)
                return@suspendCancellableCoroutine
            }

            val bufferSize = maxOf(minBufferSize, pcmData.size)

            val track =
                AudioTrack
                    .Builder()
                    .setAudioAttributes(
                        AudioAttributes
                            .Builder()
                            .setUsage(AudioAttributes.USAGE_MEDIA)
                            .setContentType(AudioAttributes.CONTENT_TYPE_SPEECH)
                            .build(),
                    ).setAudioFormat(
                        AudioFormat
                            .Builder()
                            .setEncoding(audioFormat)
                            .setSampleRate(sampleRate)
                            .setChannelMask(channelConfig)
                            .build(),
                    ).setBufferSizeInBytes(bufferSize)
                    .setTransferMode(AudioTrack.MODE_STATIC)
                    .build()

            interruptPlayback = { fail(track, AudioPlaybackException.PlaybackInterrupted) }
            audioTrack = track
            isPlaying = true

            val bytesWritten = track.write(pcmData, 0, pcmData.size)
            if (bytesWritten < 0) {
                logger.debug("[playbackId=$playbackId] completion path=write_error bytesWritten=$bytesWritten")
                fail(track, AudioPlaybackException.PlaybackFailed("Write failed: $bytesWritten"))
                return@suspendCancellableCoroutine
            }

            val bytesPerSample = bitsPerSample / 8
            val frameSize = bytesPerSample * channels
            if (frameSize <= 0 || bytesWritten % frameSize != 0) {
                logger.debug("[playbackId=$playbackId] completion path=invalid_frame frameSize=$frameSize bytesWritten=$bytesWritten")
                fail(track, AudioPlaybackException.InvalidAudioFormat)
                return@suspendCancellableCoroutine
            }

            track.notificationMarkerPosition = bytesWritten / frameSize
            track.setPlaybackPositionUpdateListener(
                object : AudioTrack.OnPlaybackPositionUpdateListener {
                    override fun onMarkerReached(track: AudioTrack?) {
                        succeed(track)
                    }

                    override fun onPeriodicNotification(track: AudioTrack?) {
                    }
                },
            )

            continuation.invokeOnCancellation {
                fail(track, AudioPlaybackException.PlaybackInterrupted)
            }

            logger.debug("[playbackId=$playbackId] track.play()")
            track.play()
        } catch (e: Exception) {
            fail(audioTrack, e)
        }
    }

    private fun parseWavHeader(data: ByteArray): WavInfo {
        if (data.size < 44) throw AudioPlaybackException.InvalidAudioFormat

        val riff = String(data.copyOfRange(0, 4))
        if (riff != "RIFF") throw AudioPlaybackException.InvalidAudioFormat

        val wave = String(data.copyOfRange(8, 12))
        if (wave != "WAVE") throw AudioPlaybackException.InvalidAudioFormat

        val channels = (data[22].toInt() and 0xFF) or ((data[23].toInt() and 0xFF) shl 8)
        val sampleRate =
            (data[24].toInt() and 0xFF) or
                ((data[25].toInt() and 0xFF) shl 8) or
                ((data[26].toInt() and 0xFF) shl 16) or
                ((data[27].toInt() and 0xFF) shl 24)
        val bitsPerSample = (data[34].toInt() and 0xFF) or ((data[35].toInt() and 0xFF) shl 8)

        if (channels !in 1..2) throw AudioPlaybackException.InvalidAudioFormat
        if (sampleRate <= 0) throw AudioPlaybackException.InvalidAudioFormat
        if (bitsPerSample !in setOf(8, 16)) throw AudioPlaybackException.InvalidAudioFormat

        var dataOffset = 12
        while (dataOffset < data.size - 8) {
            val chunkId = String(data.copyOfRange(dataOffset, dataOffset + 4))
            val chunkSize =
                (data[dataOffset + 4].toInt() and 0xFF) or
                    ((data[dataOffset + 5].toInt() and 0xFF) shl 8) or
                    ((data[dataOffset + 6].toInt() and 0xFF) shl 16) or
                    ((data[dataOffset + 7].toInt() and 0xFF) shl 24)

            if (chunkId == "data") {
                dataOffset += 8
                break
            }

            if (chunkSize < 0) throw AudioPlaybackException.InvalidAudioFormat
            val paddedChunkSize = chunkSize + (chunkSize and 1)
            val nextOffset = dataOffset.toLong() + 8L + paddedChunkSize.toLong()
            if (nextOffset <= dataOffset.toLong() || nextOffset > data.size.toLong()) {
                throw AudioPlaybackException.InvalidAudioFormat
            }
            dataOffset = nextOffset.toInt()
        }

        if (dataOffset >= data.size) throw AudioPlaybackException.InvalidAudioFormat

        return WavInfo(
            sampleRate = sampleRate,
            channels = channels,
            bitsPerSample = bitsPerSample,
            dataOffset = dataOffset,
        )
    }

    private data class WavInfo(
        val sampleRate: Int,
        val channels: Int,
        val bitsPerSample: Int,
        val dataOffset: Int,
    )
}

/**
 * Audio playback errors.
 */
sealed class AudioPlaybackException : Exception() {
    data object EmptyAudioData : AudioPlaybackException() {
        @Suppress("UnusedPrivateMember")
        private fun readResolve(): Any = EmptyAudioData

        override val message: String = "Audio data is empty"
    }

    data class PlaybackFailed(
        override val message: String?,
    ) : AudioPlaybackException()

    data object PlaybackInterrupted : AudioPlaybackException() {
        @Suppress("UnusedPrivateMember")
        private fun readResolve(): Any = PlaybackInterrupted

        override val message: String = "Audio playback was interrupted"
    }

    data object InvalidAudioFormat : AudioPlaybackException() {
        @Suppress("UnusedPrivateMember")
        private fun readResolve(): Any = InvalidAudioFormat

        override val message: String = "Invalid audio format"
    }
}