/**
 * HybridRunAnywhereCore.hpp
 *
 * Nitrogen HybridObject implementation for RunAnywhere Core SDK.
 * This single C++ file works on both iOS and Android.
 *
 * Core SDK implementation - includes:
 * - SDK Lifecycle (init, destroy)
 * - Authentication
 * - Device Registration
 * - Model Registry
 * - Download Service
 * - Storage
 * - Events
 * - HTTP Client
 * - Utilities
 * - LLM/STT/TTS/VAD/VoiceAgent (backend-agnostic via rac_*_component_* APIs)
 *
 * The capability methods (LLM, STT, TTS, VAD) are BACKEND-AGNOSTIC.
 * They call the C++ rac_*_component_* APIs which work with any registered backend.
 * Apps must install a backend package to register the actual implementation:
 * - @runanywhere/llamacpp registers the LLM backend
 * - @runanywhere/onnx registers the STT/TTS/VAD backends
 *
 * The HybridRunAnywhereCoreSpec base class is auto-generated by Nitrogen
 * from src/specs/RunAnywhereCore.nitro.ts
 */

#pragma once

// Include the generated spec header (created by nitrogen)
#if __has_include(<NitroModules/HybridObject.hpp>)
#include "HybridRunAnywhereCoreSpec.hpp"
#else
// Fallback include path during development
#include "../nitrogen/generated/shared/c++/HybridRunAnywhereCoreSpec.hpp"
#endif

#include <mutex>
#include <string>
#include <optional>
#include <variant>
#include <functional>

namespace margelo::nitro::runanywhere {

/**
 * HybridRunAnywhereCore - Core SDK native implementation
 *
 * Implements the RunAnywhereCore interface defined in RunAnywhereCore.nitro.ts
 * Delegates to modular bridges that call runanywhere-commons rac_* API.
 */
class HybridRunAnywhereCore : public HybridRunAnywhereCoreSpec {
public:
  HybridRunAnywhereCore();
  ~HybridRunAnywhereCore();

  // ============================================================================
  // SDK Lifecycle
  // ============================================================================

  std::shared_ptr<Promise<bool>> initialize(const std::string& configJson) override;
  std::shared_ptr<Promise<void>> destroy() override;
  std::shared_ptr<Promise<bool>> isInitialized() override;
  std::shared_ptr<Promise<std::string>> getBackendInfo() override;

  // ============================================================================
  // Authentication - Delegates to AuthBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> authenticate(const std::string& apiKey) override;
  std::shared_ptr<Promise<bool>> isAuthenticated() override;
  std::shared_ptr<Promise<std::string>> getUserId() override;
  std::shared_ptr<Promise<std::string>> getOrganizationId() override;
  std::shared_ptr<Promise<bool>> setAuthTokens(const std::string& authResponseJson) override;

  // ============================================================================
  // Device Registration - Delegates to DeviceBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> registerDevice(const std::string& environmentJson) override;
  std::shared_ptr<Promise<bool>> isDeviceRegistered() override;
  std::shared_ptr<Promise<bool>> clearDeviceRegistration() override;
  std::shared_ptr<Promise<std::string>> getDeviceId() override;

  // ============================================================================
  // Model Registry - Delegates to ModelRegistryBridge
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getAvailableModels() override;
  std::shared_ptr<Promise<std::string>> getModelInfo(const std::string& modelId) override;
  std::shared_ptr<Promise<bool>> isModelDownloaded(const std::string& modelId) override;
  std::shared_ptr<Promise<std::string>> getModelPath(const std::string& modelId) override;
  std::shared_ptr<Promise<bool>> registerModel(const std::string& modelJson) override;
  std::shared_ptr<Promise<std::string>> checkCompatibility(const std::string& modelId) override;

  // ============================================================================
  // Download Service - Delegates to DownloadBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> downloadModel(
    const std::string& modelId,
    const std::string& url,
    const std::string& destPath) override;
  std::shared_ptr<Promise<bool>> cancelDownload(const std::string& modelId) override;
  std::shared_ptr<Promise<std::string>> getDownloadProgress(const std::string& modelId) override;

  // ============================================================================
  // Storage - Delegates to StorageBridge
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getStorageInfo() override;
  std::shared_ptr<Promise<bool>> clearCache() override;
  std::shared_ptr<Promise<bool>> deleteModel(const std::string& modelId) override;

  // ============================================================================
  // Events - Delegates to EventBridge
  // ============================================================================

  std::shared_ptr<Promise<void>> emitEvent(const std::string& eventJson) override;
  std::shared_ptr<Promise<std::string>> pollEvents() override;

  // ============================================================================
  // HTTP Client - Delegates to HTTPBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> configureHttp(
    const std::string& baseUrl,
    const std::string& apiKey) override;
  std::shared_ptr<Promise<std::string>> httpPost(
    const std::string& path,
    const std::string& bodyJson) override;
  std::shared_ptr<Promise<std::string>> httpGet(const std::string& path) override;

  // ============================================================================
  // Utility Functions
  // ============================================================================

  std::shared_ptr<Promise<std::string>> getLastError() override;
  std::shared_ptr<Promise<bool>> extractArchive(
    const std::string& archivePath,
    const std::string& destPath) override;
  std::shared_ptr<Promise<std::string>> getDeviceCapabilities() override;
  std::shared_ptr<Promise<double>> getMemoryUsage() override;

  // ============================================================================
  // LLM Capability (Backend-Agnostic)
  // Delegates to rac_llm_component_* APIs via LLMBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> loadTextModel(
    const std::string& modelPath,
    const std::optional<std::string>& configJson) override;
  std::shared_ptr<Promise<bool>> isTextModelLoaded() override;
  std::shared_ptr<Promise<bool>> unloadTextModel() override;
  std::shared_ptr<Promise<std::string>> generate(
    const std::string& prompt,
    const std::optional<std::string>& optionsJson) override;
  std::shared_ptr<Promise<std::string>> generateStream(
    const std::string& prompt,
    const std::string& optionsJson,
    const std::function<void(const std::string&, bool)>& callback) override;
  std::shared_ptr<Promise<bool>> cancelGeneration() override;
  std::shared_ptr<Promise<std::string>> generateStructured(
    const std::string& prompt,
    const std::string& schema,
    const std::optional<std::string>& optionsJson) override;

  // ============================================================================
  // STT Capability (Backend-Agnostic)
  // Delegates to rac_stt_component_* APIs via STTBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> loadSTTModel(
    const std::string& modelPath,
    const std::string& modelType,
    const std::optional<std::string>& configJson) override;
  std::shared_ptr<Promise<bool>> isSTTModelLoaded() override;
  std::shared_ptr<Promise<bool>> unloadSTTModel() override;
  std::shared_ptr<Promise<std::string>> transcribe(
    const std::string& audioBase64,
    double sampleRate,
    const std::optional<std::string>& language) override;
  std::shared_ptr<Promise<std::string>> transcribeFile(
    const std::string& filePath,
    const std::optional<std::string>& language) override;

  // ============================================================================
  // TTS Capability (Backend-Agnostic)
  // Delegates to rac_tts_component_* APIs via TTSBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> loadTTSModel(
    const std::string& modelPath,
    const std::string& modelType,
    const std::optional<std::string>& configJson) override;
  std::shared_ptr<Promise<bool>> isTTSModelLoaded() override;
  std::shared_ptr<Promise<bool>> unloadTTSModel() override;
  std::shared_ptr<Promise<std::string>> synthesize(
    const std::string& text,
    const std::string& voiceId,
    double speedRate,
    double pitchShift) override;
  std::shared_ptr<Promise<std::string>> getTTSVoices() override;
  std::shared_ptr<Promise<bool>> cancelTTS() override;

  // ============================================================================
  // VAD Capability (Backend-Agnostic)
  // Delegates to rac_vad_component_* APIs via VADBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> loadVADModel(
    const std::string& modelPath,
    const std::optional<std::string>& configJson) override;
  std::shared_ptr<Promise<bool>> isVADModelLoaded() override;
  std::shared_ptr<Promise<bool>> unloadVADModel() override;
  std::shared_ptr<Promise<std::string>> processVAD(
    const std::string& audioBase64,
    const std::optional<std::string>& optionsJson) override;
  std::shared_ptr<Promise<void>> resetVAD() override;

  // ============================================================================
  // Secure Storage
  // Matches Swift: KeychainManager.swift
  // Uses platform adapter callbacks for Keychain/Keystore
  // ============================================================================

  std::shared_ptr<Promise<bool>> secureStorageSet(
    const std::string& key,
    const std::string& value) override;
  std::shared_ptr<Promise<std::variant<nitro::NullType, std::string>>> secureStorageGet(
    const std::string& key) override;
  std::shared_ptr<Promise<bool>> secureStorageDelete(const std::string& key) override;
  std::shared_ptr<Promise<bool>> secureStorageExists(const std::string& key) override;
  
  // Aliases for semantic clarity (forward to Set/Get implementations)
  std::shared_ptr<Promise<void>> secureStorageStore(
    const std::string& key,
    const std::string& value) override;
  std::shared_ptr<Promise<std::variant<nitro::NullType, std::string>>> secureStorageRetrieve(
    const std::string& key) override;
  std::shared_ptr<Promise<std::string>> getPersistentDeviceUUID() override;

  // ============================================================================
  // Telemetry
  // Matches Swift: CppBridge+Telemetry.swift
  // C++ handles all telemetry logic - batching, JSON building, routing
  // ============================================================================

  std::shared_ptr<Promise<void>> flushTelemetry() override;
  std::shared_ptr<Promise<bool>> isTelemetryInitialized() override;

  // ============================================================================
  // Voice Agent Capability (Backend-Agnostic)
  // Delegates to rac_voice_agent_* APIs via VoiceAgentBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> initializeVoiceAgent(const std::string& configJson) override;
  std::shared_ptr<Promise<bool>> initializeVoiceAgentWithLoadedModels() override;
  std::shared_ptr<Promise<bool>> isVoiceAgentReady() override;
  std::shared_ptr<Promise<std::string>> getVoiceAgentComponentStates() override;
  std::shared_ptr<Promise<std::string>> processVoiceTurn(const std::string& audioBase64) override;
  std::shared_ptr<Promise<std::string>> voiceAgentTranscribe(const std::string& audioBase64) override;
  std::shared_ptr<Promise<std::string>> voiceAgentGenerateResponse(const std::string& prompt) override;
  std::shared_ptr<Promise<std::string>> voiceAgentSynthesizeSpeech(const std::string& text) override;
  std::shared_ptr<Promise<void>> cleanupVoiceAgent() override;

  // ============================================================================
  // Tool Calling - Delegates to ToolCallingBridge
  // Single source of truth for parsing, formatting, and prompt building
  // Tool registry and execution are in TypeScript (RunAnywhere+ToolCalling.ts)
  // ============================================================================

  std::shared_ptr<Promise<std::string>> parseToolCallFromOutput(const std::string& llmOutput) override;
  std::shared_ptr<Promise<std::string>> formatToolsForPrompt(const std::string& toolsJson, const std::string& format) override;
  std::shared_ptr<Promise<std::string>> buildInitialPrompt(const std::string& userPrompt, const std::string& toolsJson, const std::string& optionsJson) override;
  std::shared_ptr<Promise<std::string>> buildFollowupPrompt(const std::string& originalPrompt, const std::string& toolsPrompt, const std::string& toolName, const std::string& resultJson, bool keepToolsAvailable) override;

  // ============================================================================
  // RAG Pipeline - Delegates to RAGBridge
  // ============================================================================

  std::shared_ptr<Promise<bool>> ragCreatePipeline(const std::string& configJson) override;
  std::shared_ptr<Promise<bool>> ragDestroyPipeline() override;
  std::shared_ptr<Promise<bool>> ragAddDocument(const std::string& text, const std::string& metadataJson) override;
  std::shared_ptr<Promise<bool>> ragAddDocumentsBatch(const std::string& documentsJson) override;
  std::shared_ptr<Promise<std::string>> ragQuery(const std::string& queryJson) override;
  std::shared_ptr<Promise<bool>> ragClearDocuments() override;
  std::shared_ptr<Promise<double>> ragGetDocumentCount() override;
  std::shared_ptr<Promise<std::string>> ragGetStatistics() override;

private:
  // Thread safety
  std::mutex initMutex_;

  // State tracking
  std::string lastError_;

  // Helper methods
  void setLastError(const std::string& error);
};

} // namespace margelo::nitro::runanywhere
