import Foundation
import RunAnywhere

public enum ModelFormat: String, Codable, Sendable {
    case task
    case litertlm
    case gguf
    case onnx
}

public enum DownloadState: Equatable, Sendable {
    case notDownloaded
    case downloading(progress: Double, downloaded: String, speed: String)
    case paused
    case downloaded
    case error(message: String)
}

public enum ModelCategory: String, Codable, CaseIterable, Sendable {
    case text = "Text Models"
    case multimodal = "Multimodal Models"
    case embedding = "Embedding Models"
    case imageGeneration = "Image Generation"

    public var icon: String {
        switch self {
        case .text: return "text.bubble.fill"
        case .multimodal: return "eye.fill"
        case .embedding: return "link.circle.fill"
        case .imageGeneration: return "photo.fill"
        }
    }

    public var titleKey: String {
        switch self {
        case .text: return "text_models"
        case .multimodal: return "vision_models"
        case .embedding: return "embedding_models"
        case .imageGeneration: return "image_generation_models"
        }
    }

    public var descriptionKey: String {
        switch self {
        case .text: return "text_models_description"
        case .multimodal: return "vision_models_description"
        case .embedding: return "embedding_models_description"
        case .imageGeneration: return "image_generation_models_description"
        }
    }
}

public struct ModelRequirements: Codable, Sendable {
    public let minRamGB: Int
    public let recommendedRamGB: Int
}

public struct AIModel: Identifiable, Codable, Sendable {
    public let id: String
    public let name: String
    public let description: String
    public let url: String
    public let category: ModelCategory
    public let sizeBytes: Int64
    public let source: String
    public let supportsVision: Bool
    public let supportsAudio: Bool
    public let supportsThinking: Bool
    public let supportsGpu: Bool
    public let requirements: ModelRequirements
    public let contextWindowSize: Int
    public let modelFormat: ModelFormat
    public let additionalFiles: [String]

    public init(
        id: String? = nil,
        name: String,
        description: String,
        url: String,
        category: ModelCategory,
        sizeBytes: Int64,
        source: String,
        supportsVision: Bool = false,
        supportsAudio: Bool = false,
        supportsThinking: Bool = false,
        supportsGpu: Bool = true,
        requirements: ModelRequirements,
        contextWindowSize: Int = 2048,
        modelFormat: ModelFormat = .gguf,
        additionalFiles: [String] = []
    ) {
        self.id = id ?? name.lowercased().replacingOccurrences(of: " ", with: "_")
        self.name = name
        self.description = description
        self.url = url
        self.category = category
        self.sizeBytes = sizeBytes
        self.source = source
        self.supportsVision = supportsVision
        self.supportsAudio = supportsAudio
        self.supportsThinking = supportsThinking
        self.supportsGpu = supportsGpu
        self.requirements = requirements
        self.contextWindowSize = contextWindowSize
        self.modelFormat = modelFormat
        self.additionalFiles = additionalFiles
    }

    public var sizeLabel: String {
        let formatter = ByteCountFormatter()
        formatter.allowedUnits = [.useGB, .useMB]
        formatter.countStyle = .file
        return formatter.string(fromByteCount: sizeBytes)
    }

    public var ramLabel: String {
        "\(requirements.minRamGB)GB RAM"
    }

    public var allDownloadURLs: [URL] {
        ([url] + additionalFiles).compactMap { URL(string: $0) }
    }

    public var requiredFileNames: [String] {
        allDownloadURLs.compactMap { downloadURL in
            URLComponents(url: downloadURL, resolvingAgainstBaseURL: false)?.path.split(separator: "/").last.map(String.init)
        }
    }

    public var inferenceFramework: InferenceFramework {
        modelFormat == .onnx ? .onnx : .llamaCpp
    }

    public var isDependencyOnly: Bool {
        let lowerName = name.lowercased()
        let lowerURL = url.lowercased()
        return lowerName.contains("vision projector")
            || lowerName.contains("mmproj")
            || lowerURL.contains("mmproj")
    }
}

public struct ModelData {
// AUTO-GENERATED from android ModelData.kt: GGUF + ONNX models only
public static let models: [AIModel] = [
    AIModel(
        name: "Llama-3.2 1B (IQ3_M)",
        description: "Llama 3.2 1B with IQ3_M quantization. Smallest size, great for low-memory devices. 128k context. (657MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-IQ3_M.gguf?download=true",
        category: .text,
        sizeBytes: 657000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (IQ4_XS)",
        description: "Llama 3.2 1B with IQ4_XS quantization. Optimized 4-bit. 128k context. (743MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-IQ4_XS.gguf?download=true",
        category: .text,
        sizeBytes: 743000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q3_K_L)",
        description: "Llama 3.2 1B with Q3_K_L quantization. Large 3-bit variant. 128k context. (733MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q3_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 733000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q3_K_XL)",
        description: "Llama 3.2 1B with Q3_K_XL quantization. Extra-large 3-bit variant. 128k context. (796MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q3_K_XL.gguf?download=true",
        category: .text,
        sizeBytes: 796000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_0)",
        description: "Llama 3.2 1B with Q4_0 quantization. Standard 4-bit, good balance. 128k context. (773MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 773000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_0_4_4)",
        description: "Llama 3.2 1B with Q4_0_4_4 quantization. 4-bit ARM-optimized. 128k context. (771MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_4_4.gguf?download=true",
        category: .text,
        sizeBytes: 771000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_0_4_8)",
        description: "Llama 3.2 1B with Q4_0_4_8 quantization. 4-bit ARM-optimized. 128k context. (771MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_4_8.gguf?download=true",
        category: .text,
        sizeBytes: 771000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_0_8_8)",
        description: "Llama 3.2 1B with Q4_0_8_8 quantization. 4-bit ARM-optimized. 128k context. (771MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_0_8_8.gguf?download=true",
        category: .text,
        sizeBytes: 771000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_K_L)",
        description: "Llama 3.2 1B with Q4_K_L quantization. Large K-quant 4-bit. 128k context. (871MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 871000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_K_M)",
        description: "Llama 3.2 1B with Q4_K_M quantization. Medium K-quant 4-bit, recommended. 128k context. (808MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 808000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q4_K_S)",
        description: "Llama 3.2 1B with Q4_K_S quantization. Small K-quant 4-bit. 128k context. (776MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q4_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 776000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q5_K_L)",
        description: "Llama 3.2 1B with Q5_K_L quantization. Large K-quant 5-bit. 128k context. (975MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q5_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 975000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q5_K_M)",
        description: "Llama 3.2 1B with Q5_K_M quantization. Medium K-quant 5-bit, high quality. 128k context. (912MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 912000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q5_K_S)",
        description: "Llama 3.2 1B with Q5_K_S quantization. Small K-quant 5-bit. 128k context. (893MB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q5_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 893000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q6_K)",
        description: "Llama 3.2 1B with Q6_K quantization. 6-bit, very high quality. 128k context. (1.02GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 1020000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q6_K_L)",
        description: "Llama 3.2 1B with Q6_K_L quantization. Large 6-bit, highest quality. 128k context. (1.09GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q6_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 1090000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (Q8_0)",
        description: "Llama 3.2 1B with Q8_0 quantization. 8-bit, near-original quality. 128k context. (1.32GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 1320000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 1B (f16)",
        description: "Llama 3.2 1B with f16 (full precision). Maximum quality, largest size. 128k context. (2.48GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-1B-Instruct-GGUF/resolve/main/Llama-3.2-1B-Instruct-f16.gguf?download=true",
        category: .text,
        sizeBytes: 2480000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (IQ3_M)",
        description: "Llama 3.2 3B with IQ3_M quantization. Smallest size, great for low-memory devices. 128k context. (1.6GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-IQ3_M.gguf?download=true",
        category: .text,
        sizeBytes: 1600000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (IQ4_XS)",
        description: "Llama 3.2 3B with IQ4_XS quantization. Optimized 4-bit. 128k context. (1.83GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-IQ4_XS.gguf?download=true",
        category: .text,
        sizeBytes: 1830000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q3_K_L)",
        description: "Llama 3.2 3B with Q3_K_L quantization. Large 3-bit variant. 128k context. (1.82GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q3_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 1820000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q3_K_XL)",
        description: "Llama 3.2 3B with Q3_K_XL quantization. Extra-large 3-bit variant. 128k context. (1.91GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q3_K_XL.gguf?download=true",
        category: .text,
        sizeBytes: 1910000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_0)",
        description: "Llama 3.2 3B with Q4_0 quantization. Standard 4-bit, good balance. 128k context. (1.92GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 1920000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_0_4_4)",
        description: "Llama 3.2 3B with Q4_0_4_4 quantization. 4-bit ARM-optimized. 128k context. (1.92GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_0_4_4.gguf?download=true",
        category: .text,
        sizeBytes: 1920000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_0_4_8)",
        description: "Llama 3.2 3B with Q4_0_4_8 quantization. 4-bit ARM-optimized. 128k context. (1.92GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_0_4_8.gguf?download=true",
        category: .text,
        sizeBytes: 1920000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_0_8_8)",
        description: "Llama 3.2 3B with Q4_0_8_8 quantization. 4-bit ARM-optimized. 128k context. (1.92GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_0_8_8.gguf?download=true",
        category: .text,
        sizeBytes: 1920000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_K_L)",
        description: "Llama 3.2 3B with Q4_K_L quantization. Large K-quant 4-bit. 128k context. (2.11GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 2110000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_K_M)",
        description: "Llama 3.2 3B with Q4_K_M quantization. Medium K-quant 4-bit, recommended. 128k context. (2.02GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 2020000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q4_K_S)",
        description: "Llama 3.2 3B with Q4_K_S quantization. Small K-quant 4-bit. 128k context. (1.93GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q4_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 1930000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q5_K_L)",
        description: "Llama 3.2 3B with Q5_K_L quantization. Large K-quant 5-bit. 128k context. (2.42GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q5_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 2420000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q5_K_M)",
        description: "Llama 3.2 3B with Q5_K_M quantization. Medium K-quant 5-bit, high quality. 128k context. (2.32GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 2320000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q5_K_S)",
        description: "Llama 3.2 3B with Q5_K_S quantization. Small K-quant 5-bit. 128k context. (2.27GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q5_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 2270000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q6_K)",
        description: "Llama 3.2 3B with Q6_K quantization. 6-bit, very high quality. 128k context. (2.64GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 2640000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q6_K_L)",
        description: "Llama 3.2 3B with Q6_K_L quantization. Large 6-bit, highest quality. 128k context. (2.74GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q6_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 2740000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (Q8_0)",
        description: "Llama 3.2 3B with Q8_0 quantization. 8-bit, near-original quality. 128k context. (3.42GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 3420000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Llama-3.2 3B (f16)",
        description: "Llama 3.2 3B with f16 (full precision). Maximum quality, largest size. 128k context. (6.43GB)",
        url: "https://huggingface.co/bartowski/Llama-3.2-3B-Instruct-GGUF/resolve/main/Llama-3.2-3B-Instruct-f16.gguf?download=true",
        category: .text,
        sizeBytes: 6430000000,
        source: "Meta via bartowski",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 8, recommendedRamGB: 10),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q2_K)",
        description: "IBM Granite 4.0 H-Tiny with Q2_K quantization. Smallest size. 128k context. (2.59GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q2_K.gguf?download=true",
        category: .text,
        sizeBytes: 2590000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q3_K_S)",
        description: "IBM Granite 4.0 H-Tiny with Q3_K_S quantization. Balanced size. 128k context. (3.06GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q3_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 3060000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q3_K_M)",
        description: "IBM Granite 4.0 H-Tiny with Q3_K_M quantization. Good quality. 128k context. (3.35GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q3_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 3350000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q3_K_L)",
        description: "IBM Granite 4.0 H-Tiny with Q3_K_L quantization. Better quality. 128k context. (3.6GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q3_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 3600000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q4_0)",
        description: "IBM Granite 4.0 H-Tiny with Q4_0 quantization. Good balance. 128k context. (3.96GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 3960000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q4_K_S)",
        description: "IBM Granite 4.0 H-Tiny with Q4_K_S quantization. High quality. 128k context. (4GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q4_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 4000000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q4_K_M)",
        description: "IBM Granite 4.0 H-Tiny with Q4_K_M quantization. Very high quality. 128k context. (4.23GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 4230000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q4_1)",
        description: "IBM Granite 4.0 H-Tiny with Q4_1 quantization. Enhanced quality. 128k context. (4.39GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q4_1.gguf?download=true",
        category: .text,
        sizeBytes: 4390000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q5_K_S)",
        description: "IBM Granite 4.0 H-Tiny with Q5_K_S quantization. Excellent quality. 128k context. (4.81GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q5_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 4810000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q5_0)",
        description: "IBM Granite 4.0 H-Tiny with Q5_0 quantization. Near-lossless. 128k context. (4.81GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q5_0.gguf?download=true",
        category: .text,
        sizeBytes: 4810000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q5_K_M)",
        description: "IBM Granite 4.0 H-Tiny with Q5_K_M quantization. Superior quality. 128k context. (4.95GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 4950000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q5_1)",
        description: "IBM Granite 4.0 H-Tiny with Q5_1 quantization. Premium quality. 128k context. (5.23GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q5_1.gguf?download=true",
        category: .text,
        sizeBytes: 5230000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q6_K)",
        description: "IBM Granite 4.0 H-Tiny with Q6_K quantization. Outstanding quality. 128k context. (5.71GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 5710000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 7, recommendedRamGB: 8),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (Q8_0)",
        description: "IBM Granite 4.0 H-Tiny with Q8_0 quantization. Ultimate quality. 128k context. (7.39GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 7390000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 8, recommendedRamGB: 10),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Tiny (f16)",
        description: "IBM Granite 4.0 H-Tiny with f16 (full precision). Maximum quality, largest size. 128k context. (13.9GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-tiny-GGUF/resolve/main/granite-4.0-h-tiny-f16.gguf?download=true",
        category: .text,
        sizeBytes: 13900000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q2_K)",
        description: "IBM Granite 4.0 H-Small with Q2_K quantization. Smallest size. 128k context. (11.8GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q2_K.gguf?download=true",
        category: .text,
        sizeBytes: 11800000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 12, recommendedRamGB: 14),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q3_K_S)",
        description: "IBM Granite 4.0 H-Small with Q3_K_S quantization. Balanced size. 128k context. (14.1GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q3_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 14100000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q3_K_M)",
        description: "IBM Granite 4.0 H-Small with Q3_K_M quantization. Good quality. 128k context. (15.4GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q3_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 15400000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 15, recommendedRamGB: 18),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q3_K_L)",
        description: "IBM Granite 4.0 H-Small with Q3_K_L quantization. Better quality. 128k context. (16.5GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q3_K_L.gguf?download=true",
        category: .text,
        sizeBytes: 16500000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 16, recommendedRamGB: 20),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q4_0)",
        description: "IBM Granite 4.0 H-Small with Q4_0 quantization. Good balance. 128k context. (18.3GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 18300000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 18, recommendedRamGB: 22),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q4_K_S)",
        description: "IBM Granite 4.0 H-Small with Q4_K_S quantization. High quality. 128k context. (18.4GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q4_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 18400000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 18, recommendedRamGB: 22),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q4_K_M)",
        description: "IBM Granite 4.0 H-Small with Q4_K_M quantization. Very high quality. 128k context. (19.5GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 19500000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 19, recommendedRamGB: 24),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q4_1)",
        description: "IBM Granite 4.0 H-Small with Q4_1 quantization. Enhanced quality. 128k context. (20.3GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q4_1.gguf?download=true",
        category: .text,
        sizeBytes: 20300000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 20, recommendedRamGB: 24),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q5_0)",
        description: "IBM Granite 4.0 H-Small with Q5_0 quantization. Near-lossless. 128k context. (22.2GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q5_0.gguf?download=true",
        category: .text,
        sizeBytes: 22200000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 22, recommendedRamGB: 26),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q5_K_S)",
        description: "IBM Granite 4.0 H-Small with Q5_K_S quantization. Excellent quality. 128k context. (22.2GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q5_K_S.gguf?download=true",
        category: .text,
        sizeBytes: 22200000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 22, recommendedRamGB: 26),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q5_K_M)",
        description: "IBM Granite 4.0 H-Small with Q5_K_M quantization. Superior quality. 128k context. (22.9GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 22900000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 23, recommendedRamGB: 26),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q5_1)",
        description: "IBM Granite 4.0 H-Small with Q5_1 quantization. Premium quality. 128k context. (24.2GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q5_1.gguf?download=true",
        category: .text,
        sizeBytes: 24200000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 24, recommendedRamGB: 28),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q6_K)",
        description: "IBM Granite 4.0 H-Small with Q6_K quantization. Outstanding quality. 128k context. (26.5GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 26500000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 26, recommendedRamGB: 30),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (Q8_0)",
        description: "IBM Granite 4.0 H-Small with Q8_0 quantization. Ultimate quality. 128k context. (34.3GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 34300000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 34, recommendedRamGB: 40),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Granite 4.0 H-Small (f16)",
        description: "IBM Granite 4.0 H-Small with f16 (full precision). Maximum quality, largest size. 128k context. (64.4GB)",
        url: "https://huggingface.co/ibm-granite/granite-4.0-h-small-GGUF/resolve/main/granite-4.0-h-small-f16.gguf?download=true",
        category: .text,
        sizeBytes: 64400000000,
        source: "IBM Granite",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 64, recommendedRamGB: 80),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Instruct (Q4_0)",
        description: "LiquidAI's 1.2B instruct model. Q4_0 quantization. 128k context.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF/resolve/main/LFM2.5-1.2B-Instruct-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 696000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Instruct (Q4_K_M)",
        description: "LiquidAI's 1.2B instruct model. Q4_K_M quantization. 128k context.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF/resolve/main/LFM2.5-1.2B-Instruct-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 731000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Instruct (Q8_0)",
        description: "LiquidAI's 1.2B instruct model. Q8_0 quantization. 128k context.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-GGUF/resolve/main/LFM2.5-1.2B-Instruct-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 1250000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Thinking (Q4_0)",
        description: "LiquidAI's 1.2B thinking model. Q4_0 quantization. 128k context. Supports 'thinking' mode.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-GGUF/resolve/main/LFM2.5-1.2B-Thinking-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 696000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Thinking (Q4_K_M)",
        description: "LiquidAI's 1.2B thinking model. Q4_K_M quantization. 128k context. Supports 'thinking' mode.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-GGUF/resolve/main/LFM2.5-1.2B-Thinking-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 731000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 3),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Thinking (Q8_0)",
        description: "LiquidAI's 1.2B thinking model. Q8_0 quantization. 128k context. Supports 'thinking' mode.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-GGUF/resolve/main/LFM2.5-1.2B-Thinking-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 1250000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM2-24B-A2B (Q4_0)",
        description: "LiquidAI's MoE model with 24B total parameters but only 2B active per token. Q4_0 quantization. 32k context. Multilingual (9 languages).",
        url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B-GGUF/resolve/main/LFM2-24B-A2B-Q4_0.gguf?download=true",
        category: .text,
        sizeBytes: 13500000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 16, recommendedRamGB: 18),
        contextWindowSize: 32768,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM2-24B-A2B (Q4_K_M)",
        description: "LiquidAI's MoE model with 24B total parameters but only 2B active per token. Q4_K_M quantization. 32k context. Multilingual (9 languages).",
        url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B-GGUF/resolve/main/LFM2-24B-A2B-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 14400000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 16, recommendedRamGB: 18),
        contextWindowSize: 32768,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM2-24B-A2B (Q5_K_M)",
        description: "LiquidAI's MoE model with 24B total parameters but only 2B active per token. Q5_K_M quantization for better quality. 32k context. Multilingual (9 languages).",
        url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B-GGUF/resolve/main/LFM2-24B-A2B-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 16900000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 18, recommendedRamGB: 24),
        contextWindowSize: 32768,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM2-24B-A2B (Q6_K)",
        description: "LiquidAI's MoE model with 24B total parameters but only 2B active per token. Q6_K quantization for high quality. 32k context. Multilingual (9 languages).",
        url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B-GGUF/resolve/main/LFM2-24B-A2B-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 19600000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 20, recommendedRamGB: 24),
        contextWindowSize: 32768,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM2-24B-A2B (Q8_0)",
        description: "LiquidAI's MoE model with 24B total parameters but only 2B active per token. Q8_0 quantization - near full quality. 32k context. Multilingual (9 languages).",
        url: "https://huggingface.co/LiquidAI/LFM2-24B-A2B-GGUF/resolve/main/LFM2-24B-A2B-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 25400000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 28, recommendedRamGB: 32),
        contextWindowSize: 32768,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 1.2B Instruct (ONNX Q4)",
        description: "LiquidAI's 1.2B instruction model in ONNX format. Q4 quantization for balanced quality and size. 128k context. Requires downloading 2 files.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/onnx/model_q4.onnx?download=true",
        category: .text,
        sizeBytes: 853542627,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 4),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/onnx/model_q4.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "LFM-2.5 1.2B Instruct (ONNX Q8)",
        description: "LiquidAI's 1.2B instruction model in ONNX format. Q8 quantization for higher quality. 128k context. Requires downloading 2 files.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/onnx/model_q8.onnx?download=true",
        category: .text,
        sizeBytes: 1771510908,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/onnx/model_q8.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Instruct-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "LFM-2.5 1.2B Thinking (ONNX Q4)",
        description: "LiquidAI's 1.2B reasoning model in ONNX format. Q4 quantization for balanced quality and size. 128k context. Requires downloading 2 files.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/onnx/model_q4.onnx?download=true",
        category: .text,
        sizeBytes: 853542627,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 2, recommendedRamGB: 4),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/onnx/model_q4.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "LFM-2.5 1.2B Thinking (ONNX Q8)",
        description: "LiquidAI's 1.2B reasoning model in ONNX format. Q8 quantization for higher quality. 128k context. Requires downloading 2 files.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/onnx/model_q8.onnx?download=true",
        category: .text,
        sizeBytes: 1771510908,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/onnx/model_q8.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-1.2B-Thinking-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (BF16)",
        description: "LiquidAI's 1.6B vision-language model. BF16 precision. Supports vision + text. Requires mmproj for vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/LFM2.5-VL-1.6B-BF16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2340000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (F16)",
        description: "LiquidAI's 1.6B vision-language model. F16 precision. Supports vision + text. Requires mmproj for vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/LFM2.5-VL-1.6B-F16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2340000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (Q4_0)",
        description: "LiquidAI's 1.6B vision-language model. Q4_0 quantization. Supports vision + text. Requires mmproj for vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/LFM2.5-VL-1.6B-Q4_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 696000000,
        source: "LiquidAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 4),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (Q8_0)",
        description: "LiquidAI's 1.6B vision-language model. Q8_0 quantization. Supports vision + text. Requires mmproj for vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/LFM2.5-VL-1.6B-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 1250000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 128000,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (Vision Projector, BF16)",
        description: "Vision Projector for LFM-2.5 VL models. BF16 variant required for image input. Download this to enable vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/mmproj-LFM2.5-VL-1.6b-BF16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 856000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (Vision Projector, Q8_0)",
        description: "Vision Projector for LFM-2.5 VL models. Q8_0 quantized variant for smaller size. Download this to enable vision.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-GGUF/resolve/main/mmproj-LFM2.5-VL-1.6b-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 583000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (ONNX Q4)",
        description: "LiquidAI's 1.6B vision-language model in ONNX format. Q4 quantization. Supports vision + text. Requires multiple files.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/decoder_q4.onnx?download=true",
        category: .multimodal,
        sizeBytes: 1760000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 3, recommendedRamGB: 5),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/decoder_q4.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_images_q4.onnx?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_images_q4.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/config.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "LFM-2.5 VL 1.6B (ONNX Q8)",
        description: "LiquidAI's 1.6B vision-language model in ONNX format. Q8 quantization for higher quality. Supports vision + text.",
        url: "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/decoder_q8.onnx?download=true",
        category: .multimodal,
        sizeBytes: 2540000000,
        source: "LiquidAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 128000,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/decoder_q8.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_images_q8.onnx?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_images_q8.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx_data?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/config.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/LiquidAI/LFM2.5-VL-1.6B-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (Q4_K_M)",
        description: "MistralAI's 3B instruct model. Q4_K_M quantization. 32k context. Supports Vision (Requires mmproj).",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-Q4_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2150000000,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 262144,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (Q5_K_M)",
        description: "MistralAI's 3B instruct model. Q5_K_M quantization. 32k context. Supports Vision (Requires mmproj).",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-Q5_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2470000000,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 7),
        contextWindowSize: 262144,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (Q8_0)",
        description: "MistralAI's 3B instruct model. Q8_0 quantization. 32k context. Supports Vision (Requires mmproj).",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 3650000000,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 8),
        contextWindowSize: 262144,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (Vision Projector, BF16)",
        description: "Multimodal Vision Projector for Ministral-3 3B models. Specifically the BF16 variant required for image input capabilities. Download this if you want to enable Vision for Ministral models.",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF/resolve/main/Ministral-3-3B-Instruct-2512-BF16-mmproj.gguf?download=true",
        category: .multimodal,
        sizeBytes: 842000000,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (ONNX Q4)",
        description: "MistralAI's 3B instruction model in ONNX format. Q4 quantization - recommended for mobile. 32k context. Supports vision. Requires downloading multiple files.",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/decoder_model_merged_q4.onnx?download=true",
        category: .multimodal,
        sizeBytes: 3367933870,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 32768,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/decoder_model_merged_q4.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/decoder_model_merged_q4.onnx_data_1?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/vision_encoder_q4.onnx?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/vision_encoder_q4.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/config.json?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "Ministral-3 3B Instruct (ONNX Q4F16)",
        description: "MistralAI's 3B instruction model in ONNX format. Q4F16 mixed precision - best quality/size balance. 32k context. Supports vision.",
        url: "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/decoder_model_merged_q4f16.onnx?download=true",
        category: .multimodal,
        sizeBytes: 3007199181,
        source: "MistralAI",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: false,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 32768,
        modelFormat: .onnx,
        additionalFiles: ["https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/decoder_model_merged_q4f16.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/embed_tokens_fp16.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/vision_encoder_q4.onnx?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/onnx/vision_encoder_q4.onnx_data?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/config.json?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/tokenizer.json?download=true", "https://huggingface.co/mistralai/Ministral-3-3B-Instruct-2512-ONNX/resolve/main/tokenizer_config.json?download=true"]
    ),
    AIModel(
        name: "GPT-OSS 20B (Q4_K_M)",
        description: "OpenAI's open-weight MoE model (21B total params, 3.6B active). Q4_K_M quantization. 128k context. Uses Harmony chat format. Supports reasoning modes (low/medium/high).",
        url: "https://huggingface.co/unsloth/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-Q4_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 11600000000,
        source: "OpenAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "GPT-OSS 20B (Q5_K_M)",
        description: "OpenAI's open-weight MoE model (21B total params, 3.6B active). Q5_K_M quantization for better quality. 128k context. Uses Harmony chat format. Supports reasoning modes.",
        url: "https://huggingface.co/unsloth/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-Q5_K_M.gguf?download=true",
        category: .text,
        sizeBytes: 11700000000,
        source: "OpenAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "GPT-OSS 20B (Q6_K)",
        description: "OpenAI's open-weight MoE model (21B total params, 3.6B active). Q6_K quantization for high quality. 128k context. Uses Harmony chat format. Supports reasoning modes.",
        url: "https://huggingface.co/unsloth/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-Q6_K.gguf?download=true",
        category: .text,
        sizeBytes: 12000000000,
        source: "OpenAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "GPT-OSS 20B (Q8_0)",
        description: "OpenAI's open-weight MoE model (21B total params, 3.6B active). Q8_0 quantization - near full quality. 128k context. Uses Harmony chat format. Supports reasoning modes.",
        url: "https://huggingface.co/unsloth/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-Q8_0.gguf?download=true",
        category: .text,
        sizeBytes: 12100000000,
        source: "OpenAI",
        supportsVision: false,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 14, recommendedRamGB: 16),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q2_K)",
        description: "Translate Gemma 4B with Q2_K quantization. Smallest Translate Gemma option. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q2_K.gguf?download=true",
        category: .multimodal,
        sizeBytes: 1729180160,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q3_K_L)",
        description: "Translate Gemma 4B with Q3_K_L quantization. Larger 3-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q3_K_L.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2236101120,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q3_K_M)",
        description: "Translate Gemma 4B with Q3_K_M quantization. Balanced 3-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q3_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2098475520,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q3_K_S)",
        description: "Translate Gemma 4B with Q3_K_S quantization. Small 3-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q3_K_S.gguf?download=true",
        category: .multimodal,
        sizeBytes: 1937379840,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 5),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (IQ4_XS)",
        description: "Translate Gemma 4B with IQ4_XS quantization. Efficient 4-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.IQ4_XS.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2279641600,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q4_K_S)",
        description: "Translate Gemma 4B with Q4_K_S quantization. Smaller 4-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q4_K_S.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2377945600,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q4_K_M)",
        description: "Translate Gemma 4B with Q4_K_M quantization. Recommended balance for quality and size. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q4_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2489909760,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 6),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q5_K_S)",
        description: "Translate Gemma 4B with Q5_K_S quantization. Higher-quality 5-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q5_K_S.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2764608000,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 8),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q5_K_M)",
        description: "Translate Gemma 4B with Q5_K_M quantization. High-quality 5-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q5_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2829713920,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 8),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q6_K)",
        description: "Translate Gemma 4B with Q6_K quantization. High-precision 6-bit variant. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q6_K.gguf?download=true",
        category: .multimodal,
        sizeBytes: 3190755840,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 7, recommendedRamGB: 8),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Q8_0)",
        description: "Translate Gemma 4B with Q8_0 quantization. Near full quality. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 4130417920,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 8, recommendedRamGB: 10),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (F16)",
        description: "Translate Gemma 4B with F16 precision. Highest quality and largest download. Supports text + vision and requires a separate Vision Projector (mmproj). 2k context.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.f16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 7767819520,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 12, recommendedRamGB: 16),
        contextWindowSize: 2048,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Vision Projector, Q8_0)",
        description: "Vision Projector (mmproj) required to enable image input for Translate Gemma 4B quantized variants.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.mmproj-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 591377600,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Translate Gemma 4B (Vision Projector, F16)",
        description: "Vision Projector (mmproj) required to enable image input for the F16 Translate Gemma 4B variant.",
        url: "https://huggingface.co/mradermacher/translategemma-4b-it-GGUF/resolve/main/translategemma-4b-it.mmproj-f16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 851251520,
        source: "Google via mradermacher",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma-3 4B (Q4_0, GGUF)",
        description: "Google Gemma-3 4B quantized GGUF (Q4_0). Supports text + vision — download the Vision Projector (mmproj) to enable image input.",
        url: "https://huggingface.co/google/gemma-3-4b-it-qat-q4_0-gguf/resolve/main/gemma-3-4b-it-q4_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 3155051328,
        source: "Google",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 8),
        contextWindowSize: 4096,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma-3 4B (Vision Projector, BF16)",
        description: "Vision Projector (mmproj) required to enable image input for Gemma-3 4B. BF16 variant for accurate visual encodings.",
        url: "https://huggingface.co/google/gemma-3-4b-it-qat-q4_0-gguf/resolve/main/mmproj-model-f16-4B.gguf?download=true",
        category: .multimodal,
        sizeBytes: 851251104,
        source: "Google",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma-3 12B (Q4_0, GGUF)",
        description: "Google Gemma-3 12B quantized GGUF (Q4_0). Supports text + vision — download the Vision Projector (mmproj) to enable image input.",
        url: "https://huggingface.co/google/gemma-3-12b-it-qat-q4_0-gguf/resolve/main/gemma-3-12b-it-q4_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 8074473920,
        source: "Google",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 12, recommendedRamGB: 16),
        contextWindowSize: 4096,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma-3 12B (Vision Projector, BF16)",
        description: "Vision Projector (mmproj) required to enable image input for Gemma-3 12B. BF16 variant for accurate visual encodings.",
        url: "https://huggingface.co/google/gemma-3-12b-it-qat-q4_0-gguf/resolve/main/mmproj-model-f16-12B.gguf?download=true",
        category: .multimodal,
        sizeBytes: 854200224,
        source: "Google",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    // MARK: - Gemma 4 E2B (2B active params)
    AIModel(
        name: "Gemma 4 E2B (Q3_K_M)",
        description: "Google Gemma 4 E2B with Q3_K_M quantization (2.54 GB). 2B effective active params. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q3_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 2536779136,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 4, recommendedRamGB: 6),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E2B (Q4_K_M)",
        description: "Google Gemma 4 E2B with Q4_K_M quantization (3.11 GB). Recommended balance of quality and size. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q4_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 3106731392,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E2B (Q5_K_M)",
        description: "Google Gemma 4 E2B with Q5_K_M quantization (3.36 GB). Higher-quality 5-bit variant. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q5_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 3356030336,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 5, recommendedRamGB: 7),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E2B (Q8_0)",
        description: "Google Gemma 4 E2B with Q8_0 quantization (5.05 GB). Near full quality. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/gemma-4-E2B-it-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 5048345984,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 7, recommendedRamGB: 9),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E2B (Vision Projector, F16)",
        description: "Vision Projector (mmproj) required to enable image input for Gemma 4 E2B. F16 variant for accurate visual encodings. (986 MB)",
        url: "https://huggingface.co/unsloth/gemma-4-E2B-it-GGUF/resolve/main/mmproj-F16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 985654208,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    // MARK: - Gemma 4 E4B (4B active params)
    AIModel(
        name: "Gemma 4 E4B (Q3_K_M)",
        description: "Google Gemma 4 E4B with Q3_K_M quantization (4.06 GB). 4B effective active params. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q3_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 4058130816,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 6, recommendedRamGB: 8),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E4B (Q4_K_M)",
        description: "Google Gemma 4 E4B with Q4_K_M quantization (4.98 GB). Recommended balance of quality and size. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q4_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 4977164672,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 7, recommendedRamGB: 10),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E4B (Q5_K_M)",
        description: "Google Gemma 4 E4B with Q5_K_M quantization (5.48 GB). Higher-quality 5-bit variant. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q5_K_M.gguf?download=true",
        category: .multimodal,
        sizeBytes: 5481791872,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 8, recommendedRamGB: 12),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E4B (Q8_0)",
        description: "Google Gemma 4 E4B with Q8_0 quantization (8.19 GB). Near full quality. Supports text + vision — download the Vision Projector (mmproj) to enable image input. 128k context.",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/gemma-4-E4B-it-Q8_0.gguf?download=true",
        category: .multimodal,
        sizeBytes: 8192946560,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 10, recommendedRamGB: 14),
        contextWindowSize: 131072,
        modelFormat: .gguf,
        additionalFiles: []
    ),
    AIModel(
        name: "Gemma 4 E4B (Vision Projector, F16)",
        description: "Vision Projector (mmproj) required to enable image input for Gemma 4 E4B. F16 variant for accurate visual encodings. (990 MB)",
        url: "https://huggingface.co/unsloth/gemma-4-E4B-it-GGUF/resolve/main/mmproj-F16.gguf?download=true",
        category: .multimodal,
        sizeBytes: 990372800,
        source: "Google via Unsloth",
        supportsVision: true,
        supportsAudio: false,
        supportsGpu: true,
        requirements: ModelRequirements(minRamGB: 1, recommendedRamGB: 2),
        contextWindowSize: 0,
        modelFormat: .gguf,
        additionalFiles: []
    ),
]
}
